In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import matplotlib.pyplot as plt
import pandas as pd
import networkx as nx
import numpy as np
from math import log
from CIoTS import *

In [4]:
dimensions = 3
max_p = 4
incoming_edges = 2

In [5]:
generator = CausalTSGenerator(dimensions=dimensions, max_p=max_p, data_length=10000, incoming_edges=incoming_edges)
ts = generator.generate()

In [6]:
from statsmodels.tsa.api import VAR

In [48]:
model = VAR(ts.as_matrix())
result = model.fit(5)

/home/marcus/anaconda3/lib/python3.6/site-packages/statsmodels/tsa/vector_ar/var_model.py:461: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  params = np.linalg.lstsq(z, y_sample)[0]


In [49]:
result.params.shape

(16, 3)

In [50]:
result.endog_lagged.shape

(9995, 16)

In [56]:
_, dm = transform_ts(ts, 5)

In [63]:
res = result.endog[5:] - np.dot(result.endog_lagged, result.params)

In [66]:
sse = np.dot(res.T, res)
sse

array([[9822.6199753 , 9822.67815686, 9822.58432642],
       [9822.67815686, 9823.35527745, 9822.91507622],
       [9822.58432642, 9822.91507622, 9823.00389924]])

In [65]:
result.sigma_u

array([[0.98432909, 0.98433492, 0.98432552],
       [0.98433492, 0.98440277, 0.98435866],
       [0.98432552, 0.98435866, 0.98436756]])

In [67]:
sse /(9995 - 5*3 - 1)

array([[0.98432909, 0.98433492, 0.98432552],
       [0.98433492, 0.98440277, 0.98435866],
       [0.98432552, 0.98435866, 0.98436756]])

In [78]:
y = dm[:, :3]
X = dm[:, 3:]

In [82]:
np.insert(X, 0, 1, axis=1)

array([[  1.        ,  -1.04441743,   0.60489871, ...,   1.26449565,
          1.26449565,   1.26449565],
       [  1.        ,  -1.37760315,  -0.49074672, ...,   0.38432702,
          0.38432702,  -0.37422068],
       [  1.        ,  -0.57818074,  -2.42787159, ...,  -1.47806428,
         -1.47806428,  -1.85459152],
       ...,
       [  1.        ,  -9.83147024,  26.73921809, ...,  -6.02709591,
         28.43554264,  11.58416011],
       [  1.        ,   4.26841194,  -3.90787369, ...,   2.68068093,
         -3.57534401, -18.12578146],
       [  1.        ,  -2.23419909,   6.54371416, ...,   0.97700414,
          7.68028455,   2.4461714 ]])

In [83]:
result.df_model

16

In [85]:
result.neqs

3

In [86]:
result.params.shape

(16, 3)